params:
  seed: 0

  algo:
    name: cat_a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0. # std = 1.
        fixed_sigma: True

    mlp:
      units: [512, 256, 128]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None


  load_checkpoint: False
  load_path: ''

  config:
    name: solo_cat
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False

    max_epochs: 2000
    save_best_after: 250
    save_frequency: 250
    save_intermediate: True
    save_intermediate_freq: 4000

    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: -1
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 3.e-4 # overwritten by adaptive lr_schedule
    lr_schedule: adaptive
    # schedule_type: legacy
    kl_threshold: 0.008 # target kl for adaptive lr
    grad_norm: 1.0
    entropy_coef: 0.001
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 24 # 24 for t = 0.02 (decimation = 4)
    minibatch_size: 16384 # 16384 for horizon_length 24
    mini_epochs: 5
    critic_coef: 2
    clip_value: True
    bounds_loss_coef: 0.0

    print_stats: False

    player:
      deterministic: True
      use_vecenv: True
      games_num: 2000
      print_stats: False
    
    clip_actions: False